name: Build and Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: dlsmdar.azurecr.io
          username: ${{ secrets.AZURE_ACR_USERNAME }}
          password: ${{ secrets.AZURE_ACR_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker buildx create --use
          docker buildx inspect --bootstrap
          docker buildx build --platform linux/amd64,linux/arm64 -t dlsmdar.azurecr.io/dls-frontend:${{ github.sha }} --build-arg REACT_APP_AUTH_URL=${{ secrets.REACT_APP_AUTH_URL }} --build-arg REACT_APP_CUSTOMER_INVENTORY_URL=${{ secrets.REACT_APP_CUSTOMER_INVENTORY_URL }} ./dls-frontend --push
